client_id = "04d5f115df0f3d42a6a4a17ca7c17f59"
application_url = "https://qr-code-1-nine.vercel.app"
embedded = true
name = "qr-app"
handle = "qr-app-144"

[build]
include_config_on_deploy = true
dev_store_url = "amogademo.myshopify.com"

[webhooks]
api_version = "2025-01"

[access_scopes]
scopes = "write_products,write_orders,write_customers"

[auth]
redirect_urls = [
  "https://qr-code-1-nine.vercel.app/auth/callback",
  "https://qr-code-1-nine.vercel.app/auth/shopify/callback",
  "https://qr-code-1-nine.vercel.app/api/auth/callback"
]

[pos]
embedded = false