client_id = "c04a94e36de14a5ea864d190b67aae9b"
application_url = "https://qr-code-1-nine.vercel.app"
embedded = true
name = "qr-code"
handle = "qr-code-416"


[build]
include_config_on_deploy = true
dev_store_url = "amogademo.myshopify.com"

[webhooks]
api_version = "2025-01"

[access_scopes]
scopes = "write_products"

[auth]
redirect_urls = [
  "https://qr-code-1-nine.vercel.app/auth/callback",
  "https://qr-code-1-nine.vercel.app/auth/shopify/callback",
  "https://qr-code-1-nine.vercel.app/api/auth/callback"
]

[pos]
embedded = false