# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3edfa23911dcd39ed5767844bd92867a"
application_url = "https://blades-species-specialties-drill.trycloudflare.com"
embedded = true
name = "qr-app"
handle = "qr-app-144"

[build]
include_config_on_deploy = true
dev_store_url = "amogademo.myshopify.com"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://blades-species-specialties-drill.trycloudflare.com/auth/callback",
  "https://blades-species-specialties-drill.trycloudflare.com/auth/shopify/callback",
  "https://blades-species-specialties-drill.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
